### ISSUE TITLE
Can the package be extended to account for async Flask endpoints

### ISSUE THREAD

**Issue by mrcrittall2016** [antarctica/flask-entra-auth#29]
Can the package be extended to account for async Flask endpoints.

Currently the decorator fails to "await" a coroutine or asynchronous process.

**Comment by felnne** [comment]
Hi sorry for not replying to this issue and it's likely too late now but I don't have a huge amount of experience with async Python.

If AuthLib supports this then I expect the validation this package does can be made to work with that (it does make HTTP calls itself to get the OIDC metadata and JWKS but those could be rewritten).

It's not something I'd be able to add due to time pressures but I'm happy to work together on a contribution.

If that's of use please re-open this issue.
